# Generated by Django 6.0.3 on 2026-03-11 15:27

from django.db import migrations, models

def assign_college_ids(apps, schema_editor):
    import sqlite3, os
    db_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), 'db.sqlite3')
    conn = sqlite3.connect(db_path)
    cursor = conn.cursor()
    cursor.execute("SELECT id FROM accounts_collegeprofile ORDER BY id")
    rows = cursor.fetchall()
    for i, (pk,) in enumerate(rows, start=1):
        cursor.execute("UPDATE accounts_collegeprofile SET college_id=? WHERE id=?", (f'CLG{i:05d}', pk))
    conn.commit()
    conn.close()
class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_studentprofile_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeprofile',
            name='accreditation',
        ),
        migrations.RemoveField(
            model_name='collegeprofile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='collegeprofile',
            name='total_departments',
        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='college_id',
            field=models.CharField(blank=True, max_length=20, unique=True),

        ),
        migrations.AddField(
            model_name='collegeprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='collegeprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='batch_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, unique=True),

        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='designation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='employee_id',
            field=models.CharField(blank=True, max_length=20, unique=True),

        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('college', 'College'), ('teacher', 'Teacher'), ('student', 'Student')], default='student', max_length=20),
        ),
    ]
