# Generated by Django 6.0.3 on 2026-03-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_collegeprofile_accreditation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegeprofile',
            name='slug',
            field=models.SlugField(blank=True, help_text='Short code for URL e.g. ACE, NIT, DIT', max_length=20, unique=True),
        ),
    ]
