# Generated by Django 6.0.3 on 2026-03-12 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_exam_cancellation_reason_exam_postponed_date_and_more'),
        ('accounts', '0004_collegeprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='assigned_teachers', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_teachers', to='academics.department'),
        ),
    ]
