# Generated by Django 6.0.3 on 2026-04-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_teacherprofile_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='last_semester_update',
            field=models.DateField(blank=True, null=True),
        ),
    ]
