# Generated by Django 6.0.3 on 2026-03-11 06:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_notices', to=settings.AUTH_USER_MODEL),
        ),
    ]
