# Generated by Django 6.0.3 on 2026-04-08 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_exam_cancellation_reason_exam_postponed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('partial', 'Partial'), ('overpaid', 'Overpaid')], default='pending', max_length=20),
        ),
    ]
