# Generated by Django 6.0.3 on 2026-04-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_feepayment_status'),
        ('accounts', '0008_remove_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='shared_courses', to='accounts.teacherprofile'),
        ),
    ]
