# Generated by Django 6.0.3 on 2026-04-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_course_teachers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='teachers',
        ),
    ]
